#!/usr/bin/env bash
# Hyprwwland > by darkmaster grm34.

set -e

# Configuration.
user="keyzer"
email="keyzer@no6tem.work"
host="arch6tem"
timezone="Europe/Paris"
lang="en_US.UTF-8"
keymap="fr"
font="Lat2-Terminus16"
boot="/dev/sda1"
swap="/dev/sda2"
root="/dev/sda3"
microcode="intel-ucode"
dotfiles="https://github.com/grm34/Hyprwwland-dotfiles"

# Usage.
printf -v usage '%s\n' "
  # From USB Live
  Install Arch Linux base:      bash arch6tem install base
  
  # From Arch Linux
  Install AUR Helper:           bash arch6tem install aur_helper
  Install Firmware Modules:     bash arch6tem install firmware_modules
  Install Sound System:         bash arch6tem install sound_system
  Install Intel GPU Drivers:    bash arch6tem install intel_gpu_drivers
  Install Window Manager:       bash arch6tem install window_manager
  Install Multimedia Support:   bash arch6tem install multimedia_support
  Install Fonts and Themes:     bash arch6tem install fonts_themes
  Install User Applications:    bash arch6tem install user_apps
  Install Android Support:      bash arch6tem install android_support
  Install Dev Tools:            bash arch6tem install dev_tools
  Install Dotfiles:             bash arch6tem install dotfiles"

###################
# Arch Linux Base #
###################

base() {
  timedatectl set-timezone "$timezone"

  # Format and mount partitions.
  mkfs.fat -F 32 "$boot"
  mkswap "$swap"
  mkfs.ext4 "$root"
  mount "$root" /mnt
  mount --mkdir "$boot" /mnt/boot
  swapon "$swap"

  # Install base system.
  pacstrap -K /mnt base base-devel linux linux-firmware
  genfstab -U /mnt >> /mnt/etc/fstab
  chroot() { arch-chroot /mnt /bin/bash -c "$@"; }

  # Configure.
  ln -sf /mnt/usr/share/zoneinfo/"$timezone"\
    /mnt/etc/localtime
  sed -i "s/#${lang} UTF-8/${lang} UTF-8/g" /mnt/etc/locale.gen
  chroot "locale-gen"
  printf '%s' "LANG=$lang" > /mnt/etc/locale.conf
  printf '%s\n%s' "KEYMAP=$keymap" "FONT=$font"\
    > /mnt/etc/vconsole.conf
  printf '%s' "$host" > /mnt/etc/hostname
  printf '%s\n%s\n%s' "127.0.0.1 localhost"\
    "::1       localhost" "127.0.1.1 $host.localdomain $host"\
    > /mnt/etc/hosts
  sed -i "s/#Color/Color/g" /mnt/etc/pacman.conf
  sed -i\
    "s/Architecture = auto/Architecture = auto\nILoveCandy/g"\
    /mnt/etc/pacman.conf

  # Install requirements.
  chroot "pacman --needed --noconfirm -S $microcode\
    reflector hdparm networkmanager man man-db"
  chroot "systemctl enable NetworkManager.service"
  chroot "systemctl enable reflector.timer"
  chroot "systemctl enable fstrim.timer"
  chroot "mkinitcpio -P"

  # Install bootloader.
  chroot "bootctl install"
  local uuid
  uuid="$(blkid | grep $root | cut -d ' ' -f 2)"
  printf '%s\n%s\n%s\n%s' "default arch.conf" "timeout 3"\
    "console-mode max" "editor no" > /mnt/boot/loader/loader.conf
  printf '%s\n%s\n%s\n%s\n%s' "title Arch Linux"\
    "linux /vmlinuz-linux" "initrd /${microcode}.img"\
    "initrd /initramfs-linux.img"\
    "options root=\"${uuid//\"}\" rw i915.enable_dpcd_backlight=1"\
    > /mnt/boot/loader/entries/arch.conf
  cp /mnt/boot/loader/entries/arch.conf\
    /mnt/boot/loader/entries/arch-fallback.conf
  sed -i "s/Arch Linux/Arch Linux (fallback initramfs)/g"\
    /mnt/boot/loader/entries/arch-fallback.conf
  sed -i "s/initramfs-linux/initramfs-linux-fallback/g"\
    /mnt/boot/loader/entries/arch-fallback.conf

  # Create user.
  chroot "useradd -m $user"
  printf '\n%s\n%s' "$user ALL=(ALL:ALL) ALL"\
    "$user $host=(ALL) NOPASSWD: /usr/bin/paru" >> /mnt/etc/sudoers
  chroot "usermod -aG video,systemd-journal $user"
  printf '\n%s' "Enter a password for root !"
  chroot "passwd"
  printf '\n%s' "Enter a password for $user !"
  chroot "passwd $user"
  cp arch6tem /mnt/home/"$user"/arch6tem
  chroot "chown $user:$user /home/$user/arch6tem"

  # Reboot.
  umount -R /mnt
  swapoff "$swap"
  printf '\n%s\n' "arch6tem: successful installation (reboot)"
}

####################
# User Environment #
####################

aur_helper() {
  # Including: git cmake and rustup.
  sudo timedatectl set-timezone "$timezone"
  sudo pacman --noconfirm --needed -S git cmake rustup
  rustup default stable
  cd && git clone https://aur.archlinux.org/paru-git.git
  cd paru-git && makepkg -si
  cd && rm -rf paru-git
}

firmware_modules() {
  paru --needed -S mkinitcpio-firmware mkinitcpio-numlock
  sudo sed -i "s/consolefont block/consolefont numlock block/g"\
    /etc/mkinitcpio.conf
}

sound_system() {
  sudo pacman --noconfirm --needed -S\
    pipewire pipewire-audio pipewire-alsa\
    pipewire-pulse pipewire-jack wireplumber\
    pulsemixer myxer-bin
}

intel_gpu_drivers() {
  sudo pacman --noconfirm --needed -S\
    mesa intel-media-driver intel-gpu-tools\
    vulkan-intel vulkan-tools
}

window_manager() {
  # Including:
  # - desktop widgets
  # - desktop notifications
  # - primary clipboard
  # - system idle
  # - screen capture
  # - brightness control
  # - desktop wallpapers
  # - GUI support (GTK/Qt)
  # - app launcher
  paru --needed -S\
    hyprland eww-wayland dunst libnotify libcanberra\
    wl-clipboard cliphist swayidle swaylock-effects-git\
    grim slurp hyprshot light duf jaq neofetch hyprpaper\
    qt5-wayland qt6-wayland xdg-desktop-portal-hyprland\
    gtk3 gtk4 nwg-look-bin qt5ct qt6ct fuzzel
  printf '%s' "
HYPRSHOT_DIR='pictures/screenshots'
GDK_BACKEND='wayland,x11'
SDL_VIDEODRIVER='wayland'
CLUTTER_BACKEND='wayland'
WINIT_UNIX_BACKEND='wayland'
XDG_CURRENT_DESKTOP='Hyprland'
XDG_SESSION_TYPE='wayland'
XDG_SESSION_DESKTOP='Hyprland'
QT_AUTO_SCREEN_SCALE_FACTOR='1'
QT_QPA_PLATFORM='wayland;xcb'
QT_WAYLAND_DISABLE_WINDOWDECORATION='1'
QT_QPA_PLATFORMTHEME='qt6ct' " >> "$HOME/environment"
  sudo mv "$HOME/environment" /etc/environment
}

multimedia_support() {
  sudo pacman --noconfirm --needed -S\
    ffmpeg gstreamer gsound gst-libav gst-plugins-base\
    gst-plugins-good gst-plugins-bad gst-plugins-ugly\
    mediainfo mpv
}

fonts_themes() {
  paru --needed -S\
    awesome-terminal-fonts ttf-terminus-nerd noto-fonts\
    ttf-noto-nerd noto-fonts-emoji ttf-anonymouspro-nerd\
    ttf-ubuntu-nerd ttf-meslo-nerd ttf-jetbrains-mono-nerd\
    ttf-nerd-fonts-symbols ttf-nerd-fonts-symbols-mono\
    papirus-icon-theme capitaine-cursors breeze-gtk\
    adwaita-qt5 adwaita-qt6 sound-theme-freedesktop
}

user_apps() {
  paru --needed -S\
    alacritty zellij nushell starship vivid zoxide htop btop\
    helix felix-rs chafa most git-delta bat bandwhich exa\
    feh gimp librewolf-bin zathura zathura-pdf-mupdf\
    wayfarer gajim-git himalaya gnupg pass hyprpicker\
    hyperfine sniffnet filezilla
}

android_support() {
  paru --needed -S\
    android-sdk-platform-tools android-file-transfer
}

dev_tools() {
  paru --needed -S\
    bash-language-server bash-completion shellcheck tokei\
    vscode-css-languageserver vscode-json-languageserver\
    yaml-language-server marksman-bin rust-analyzer
  cargo install --git https://github.com/euclio/mdpls
}

dotfiles() {
  paru --needed -S github-cli chezmoi
  chezmoi init "$dotfiles"
  chezmoi apply
  chsh -s /bin/nu
  systemctl --user enable --now himalaya.service
  systemctl --user enable --now himalaya-watch.service
  gpg --full-gen-key
  pass init "$user"
  pass insert "$email"
}

################
# Run arch6tem #
################

case "$@" in
  "install base") base ;;
  "install aur_helper") aur_helper ;;
  "install firmware_modules") firmware_modules ;;
  "install sound_system") sound_system ;;
  "install intel_gpu_drivers") intel_gpu_drivers ;;
  "install window_manager") window_manager ;;
  "install multimedia_support") multimedia_support ;;
  "install fonts_themes") fonts_themes ;;
  "install user_apps") user_apps ;;
  "install android_support") android_support ;;
  "install dev_tools") dev_tools ;;
  "install dotfiles") dotfiles ;;
  *) printf '%s' "$usage"
esac

